applicants = [
        {'application_code': 'thc420',
         'first_name': 'Bob',
         'last_name': 'Marley',
         'email': "420everyday@blazeit.com",
         'year_of_birth': 1966,
         'gender': 'male',
         'city': 'Jamaica',
         'assigned_school': 'Codecool Budapest',
         'status': 'accepted'},

        {'application_code': 'dev666',
         'first_name': 'Devil',
         'last_name': 'Lawyer',
         'email': "itsgettinghothere@hell.com",
         'year_of_birth': 1966,
         'gender': 'male',
         'city': 'Hell',
         'assigned_school': 'Codecool Budapest',
         'status': 'rejected'},

        {'application_code': 'nir333',
         'first_name': 'Curt',
         'last_name': 'Cobain',
         'email': "penny@royal.tea",
         'year_of_birth': 1967,
         'gender': 'male',
         'city': 'Rome',
         'assigned_school': 'Codecool Budapest',
         'status': 'in progress'},

        {'application_code': None,
         'first_name': 'Pam',
         'last_name': 'Pam',
         'email': "szeretem@acsokit.com",
         'year_of_birth': 1993,
         'gender': 'notsure',
         'city': 'Győr',
         'assigned_school': None,
         'status': 'new'},

        {'application_code': None,
         'first_name': 'Frodo',
         'last_name': 'Baggins',
         'email': "gottogo@tothevolcano.com",
         'year_of_birth': 2000,
         'gender': 'male',
         'city': 'Debrecen',
         'assigned_school': None,
         'status': 'new'},

        {'application_code': None,
         'first_name': 'Elvis',
         'last_name': 'Presley',
         'email': "ohlook@myhair.com",
         'year_of_birth': 1935,
         'gender': 'male',
         'city': 'Barcelona',
         'assigned_school': None,
         'status': 'new'},

        {'application_code': None,
         'first_name': 'Andreste',
         'last_name': 'Éimhear',
         'email': "boudicca@rules.com",
         'year_of_birth': 1909,
         'gender': 'female',
         'city': 'Budapest',
         'assigned_school': None,
         'status': 'new'},

        {'application_code': None,
         'first_name': 'Jean',
         'last_name': 'D\'Arc',
         'email': "feminism@isnotdead.com",
         'year_of_birth': 1412,
         'gender': 'female',
         'city': 'Paris',
         'assigned_school': None,
         'status': 'new'},

        {'application_code': None,
         'first_name': 'Krystyna',
         'last_name': 'Rudaski',
         'email': "krystyna.rudaski@gmail.com",
         'year_of_birth': 1980,
         'gender': 'female',
         'city': 'Krakow',
         'assigned_school': None,
         'status': 'new'}
    ]


cities = [
        {'city': 'Budapest',
         'nearest_school': 'Codecool Budapest'},
        {'city': 'Miskolc',
         'nearest_school': 'Codecool Miskolc'},
        {'city': 'Krakow',
         'nearest_school': 'Codecool Krakow'},
        {'city': 'Madrid',
         'nearest_school': 'Codecool Madrid'},
        {'city': 'Eger',
         'nearest_school': 'Codecool Miskolc'},
        {'city': 'Debrecen',
         'nearest_school': 'Codecool Miskolc'},
        {'city': 'Warsaw',
         'nearest_school': 'Codecool Krakow'},
        {'city': 'Barcelona',
         'nearest_school': 'Codecool Madrid'},
        {'city': 'Győr',
         'nearest_school': 'Codecool Budapest'},
        {'city': 'Paris',
         'nearest_school': 'Codecool Madrid'},
        {'city': 'Rome',
         'nearest_school': 'Codecool Budapest'},
        {'city': 'St. Petersburg',
         'nearest_school': 'Codecool Krakow'}
    ]


interviews = [
        {'date_time': '2016-11-20 10:00:00',
         'duration': 2,
         'mentor': 'Beothy',
         'free': True},
        {'date_time': '2016-11-27 10:00:00',
         'duration': 2,
         'mentor': 'Tompa',
         'free': True},
        {'date_time': '2016-12-24 14:00:00',
         'duration': 2,
         'mentor': 'Salamon',
         'free': True},
        {'date_time': '2016-12-11 14:00:00',
         'duration': 2,
         'mentor': 'Balogh',
         'free': True},
        {'date_time': '2017-1-4 10:00:00',
         'time': '10:00',
         'duration': 2,
         'mentor': 'Bullshitowski',
         'free': True},
        {'date_time': '2017-1-12 15:00:00',
         'duration': 2,
         'mentor': 'Conda',
         'free': True},
        {'date_time': '2017-1-20 14:00:00',
         'duration': 2,
         'mentor': 'Orlando',
         'free': True},
        {'date_time': '2016-10-20 10:00:00',
         'duration': 2,
         'mentor': 'Algalwillow',
         'free': True},
        {'date_time': '2016-11-15 8:00:00',
         'duration': 2,
         'mentor': 'Marshmallow',
         'free': True}
    ]


mentors = [
        {'first_name': 'Miklos',
         'last_name': 'Beothy',
         'school_id': 1},
        {'first_name': 'Daniel',
         'last_name': 'Salamon',
         'school_id': 1},
        {'first_name': 'Tamas',
         'last_name': 'Tompa',
         'school_id': 1},
        {'first_name': 'Stanislaw',
         'last_name': 'Bullshitowski',
         'school_id': 3},
        {'first_name': 'Anna',
         'last_name': 'Conda',
         'school_id': 4},
        {'first_name': 'Tibor',
         'last_name': 'Balogh',
         'school_id': 2},
        {'first_name': 'Ethel',
         'last_name': 'Orlando',
         'school_id': 4},
        {'first_name': 'Grandmaster',
         'last_name': 'Algalwillow',
         'school_id': 3},
        {'first_name': 'Pumpkin',
         'last_name': 'Marshmallow',
         'school_id': 2}
    ]


schools =[
        {'name': 'Codecool Budapest'},
        {'name': 'Codecool Miskolc'},
        {'name': 'Codecool Krakow'},
        {'name': 'Codecool Madrid'}
    ]
